[FILTER]
    Name    lua
    Match   keyboard.logs
    script  /fluent-bit/etc/strip_path.lua
    call    strip_path

[SERVICE]
    Flush           1
    Log_Level       info
    Parsers_File    parsers.conf 

[INPUT]
    Name            tail
    Path            /var/log/keyboard/*.log
    Path_Key        filename
    Tag             keyboard.logs
    Read_from_Head  True
    DB              /var/log/flb_keyboard.db

[OUTPUT]
    Name            loki
    Match           *
    Host            loki
    Port            3100
    Labels          job=fluentbit, source=keyboard_telemetry
    Label_Keys  $filename
    auto_kubernetes_labels off
